Future Skills Summer Camp on Generative AI ✨

Step into the world of Generative AI and explore the future of technology! 🚀
Join our exclusive Summer Camp.

📅 Date: 27–30 April 2026
🕒 Time: 9:30 AM–4:00 PM
🎯 Students (Age 14–18)
🤝 In association with NSDC

Course Details: https://drive.google.com/file/d/1LxT5iM7vOKBPjcTPUUHGalEfH1CpUo3D/view?usp=sharing 

💰 Course Fees: ₹2000

🔗 Register here: https://forms.gle/F4cXCJ3NwVg9c4bX6

📞9947442092 / 9446429980

✨Food & Transportation Facility will be provided.

⚡Limited Seats–Register Early!